-- Anime Squadron static data file
-- Generated from game scripts. Set NS.rebuildData = true before executing to regenerate.
return {

    -- Which units can awaken and what they cost
    -- Gold is excluded (universal currency, always grindable)
    awaken = {
        ["Shinks"]              = { awakensTo="Shinks (Emperor)",          cost={["Pelli"]=100,["Beastblood Catalyst"]=20,["King's Haki Residue"]=3,["Stormwake Sailcloth"]=40,["Meat"]=200,["Gryphon"]=1} },
        ["Big Beard"]           = { awakensTo="Big Beard (Father)",        cost={["Pelli"]=100,["Beastblood Catalyst"]=10,["Depthglass Bottle"]=50,["Bisento"]=1,["Meat"]=200,["Stormwake Sailcloth"]=100} },
        ["Vegata (SSJ4)"]       = { awakensTo="Vegata (SSJ4 Full Power)",  cost={["Stellar Ki Quartz"]=50,["Limitbreak Obsidian"]=30,["Zeni"]=100,["Scouter"]=1,["Ki Resonant Crystal"]=70,["Senzu"]=200} },
        ["Rizzuto"]             = { awakensTo="Rizzuto (Sage)",            cost={["Shuriken"]=1,["Narutomaki"]=200,["Genjutsu Fog Vial"]=30,["Headband"]=100,["Binding Cloth"]=50,["Shinobi Bone"]=100} },
        ["Woo"]                 = { awakensTo="Woo (Shadow)",              cost={["Eclipse Godstone"]=5,["Pelli"]=100,["Chakra Fragment"]=5,["King's Haki Residue"]=5,["Monarch Daggers"]=1,["Zeni"]=100,["Headband"]=100} },
        ["Super Beby 2"]        = { awakensTo="Big Beard (Father)",        cost={["Beastblood Catalyst"]=5,["Depthglass Bottle"]=25,["Bisento"]=1,["Meat"]=100,["Stormwake Sailcloth"]=50} },
        ["Madora"]              = { awakensTo="Madora (Gunbai)",           cost={["Gunbai"]=1,["Narutomaki"]=200,["Genjutsu Fog Vial"]=50,["Headband"]=200,["Chakra Fragment"]=6,["Fuin Script Paper"]=30} },
        ["Karashi"]             = { awakensTo="Karashi (Sharingan)",       cost={["Chakra Fragment"]=3,["Karashi's Book"]=1,["Fuin Script Paper"]=20,["Headband"]=100,["Shinobi Bone"]=100,["Narutomaki"]=200} },
        ["Goki (SSJ4 Full Power)"] = { awakensTo="Gometa (SSJ4)",         cost={["Eclipse Godstone"]=10,["King's Haki Residue"]=10,["Chakra Fragment"]=10,["Zeni"]=200,["Primal Core"]=1} },
        ["Goki (SSJ4)"]         = { awakensTo="Goki (SSJ4 Full Power)",   cost={["Eclipse Godstone"]=3,["Zenkai Ore"]=100,["Limitbreak Obsidian"]=20,["Zeni"]=100,["Power Pole"]=1,["Senzu"]=200} },
        ["Shanron"]             = { awakensTo="Shanron (Omega)",           cost={["Eclipse Godstone"]=10,["King's Haki Residue"]=10,["Chakra Fragment"]=10,["Dragonballs"]=1,["Zeni"]=200} },
        ["Puppeteer"]           = { awakensTo="Puppeteer (Transcendent)",  cost={["Eclipse Godstone"]=10,["Pelli"]=100,["Chakra Fragment"]=10,["King's Haki Residue"]=10,["Headband"]=100,["Hogyoku Orb"]=1,["Zeni"]=100} },
        ["Berserker"]           = { awakensTo="Berserker (Enraged)",       cost={["Moonlit Silver"]=30,["Dragon Slayer (Evo)"]=1,["Black Sun Amber"]=15,["Apostle Iron"]=100,["Eclipse Stone"]=75,["Brand Ash"]=50,["Behelit"]=200,["White Behelit"]=50} },
        ["Caska"]               = { awakensTo="Caska (Resiliance)",        cost={["Moonlit Silver"]=20,["Behelit"]=100,["Black Sun Amber"]=5,["Apostle Iron"]=75,["Eclipse Stone"]=50,["Brand Ash"]=30,["Caskas Sword"]=1,["White Behelit"]=25} },
        ["Skeleton Knight"]     = { awakensTo="Skeleton Knight (Resonance)",cost={["Sword Of Resonance"]=1,["Behelit"]=200,["Black Sun Amber"]=15,["Apostle Iron"]=100,["Eclipse Stone"]=75,["Brand Ash"]=50,["Moonlit Silver"]=30,["White Behelit"]=25} },
        ["Falcon"]              = { awakensTo="Falcon (Dark)",             cost={["Moonlit Silver"]=30,["Behelit"]=200,["Black Sun Amber"]=15,["Cavalry Saber"]=1,["Apostle Iron"]=100,["Eclipse Stone"]=75,["Brand Ash"]=50,["White Behelit"]=50} },
        ["Baras"]               = { awakensTo="Baras (Meteoric Burst)",    cost={["Black Sun Amber"]=10,["Pelli"]=100,["Chakra Fragment"]=10,["King's Haki Residue"]=10,["Headband"]=100,["Behelit"]=100,["Baras Eye"]=1} },
        ["Garu"]                = { awakensTo="Garu (Half Monster)",       cost={["Black Sun Amber"]=10,["Pelli"]=100,["Chakra Fragment"]=10,["King's Haki Residue"]=10,["Headband"]=100,["Behelit"]=100,["Hunters Cloth"]=1} },
    },

    -- Items that have no known farmable stage source (event/quest/story one-time)
    unknownSource = {
        "Monarch Daggers", "Primal Core", "Hogyoku Orb", "Baras Eye", "Hunters Cloth",
        "Gold",  -- universal currency
    },

    -- Material -> list of stages that drop it
    -- Each entry: {world, mode, diff, act, amount, chance, pity?}
    matmap = {
        ["Apostle Iron"]         = { {world="Eclipse (Before)",mode="Story",diff="Normal",act=1,amount="2-4x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Normal",act=2,amount="2-4x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Hard",act=1,amount="4-8x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Hard",act=2,amount="4-8x",chance="100%"} },
        ["Zenkai Ore"]           = { {world="GT City",mode="Story",diff="Normal",act=1,amount="2-4x",chance="100%"},{world="GT City",mode="Story",diff="Normal",act=2,amount="2-4x",chance="100%"},{world="GT City",mode="Story",diff="Hard",act=1,amount="4-8x",chance="100%"},{world="GT City",mode="Story",diff="Hard",act=2,amount="4-8x",chance="100%"} },
        ["Ki Resonant Crystal"]  = { {world="GT City",mode="Story",diff="Normal",act=3,amount="1-2x",chance="100%"},{world="GT City",mode="Story",diff="Normal",act=4,amount="1-2x",chance="100%"},{world="GT City",mode="Story",diff="Hard",act=3,amount="2-4x",chance="100%"},{world="GT City",mode="Story",diff="Hard",act=4,amount="2-4x",chance="100%"} },
        ["Stellar Ki Quartz"]    = { {world="GT City",mode="Story",diff="Normal",act=5,amount="1x",chance="100%"},{world="GT City",mode="Story",diff="Normal",act=6,amount="1x",chance="100%"},{world="GT City",mode="Story",diff="Hard",act=5,amount="2x",chance="100%"},{world="GT City",mode="Story",diff="Hard",act=6,amount="2x",chance="100%"} },
        ["Limitbreak Obsidian"]  = { {world="GT City",mode="Story",diff="Normal",act=7,amount="1x",chance="30%"},{world="GT City",mode="Story",diff="Normal",act=8,amount="1x",chance="30%"},{world="GT City",mode="Story",diff="Hard",act=7,amount="1x",chance="60%"},{world="GT City",mode="Story",diff="Hard",act=8,amount="1x",chance="60%"} },
        ["Eclipse Godstone"]     = { {world="GT City",mode="Story",diff="Normal",act=9,amount="1x",chance="3%",pity=30},{world="GT City",mode="Story",diff="Normal",act=10,amount="1x",chance="3%",pity=30},{world="GT City",mode="Story",diff="Hard",act=9,amount="1x",chance="6%",pity=15},{world="GT City",mode="Story",diff="Hard",act=10,amount="1x",chance="6%",pity=15} },
        ["Currentbinder Rope"]   = { {world="Marine Lobby",mode="Story",diff="Normal",act=1,amount="2-4x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Normal",act=2,amount="2-4x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Hard",act=1,amount="4-8x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Hard",act=2,amount="4-8x",chance="100%"} },
        ["Depthglass Bottle"]    = { {world="Marine Lobby",mode="Story",diff="Normal",act=3,amount="1-2x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Normal",act=4,amount="1-2x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Hard",act=3,amount="2-4x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Hard",act=4,amount="2-4x",chance="100%"} },
        ["Stormwake Sailcloth"]  = { {world="Marine Lobby",mode="Story",diff="Normal",act=5,amount="1x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Normal",act=6,amount="1x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Hard",act=5,amount="2x",chance="100%"},{world="Marine Lobby",mode="Story",diff="Hard",act=6,amount="2x",chance="100%"} },
        ["Beastblood Catalyst"]  = { {world="Marine Lobby",mode="Story",diff="Normal",act=7,amount="1x",chance="30%"},{world="Marine Lobby",mode="Story",diff="Normal",act=8,amount="1x",chance="30%"},{world="Marine Lobby",mode="Story",diff="Hard",act=7,amount="1x",chance="60%"},{world="Marine Lobby",mode="Story",diff="Hard",act=8,amount="1x",chance="60%"} },
        ["King's Haki Residue"]  = { {world="Marine Lobby",mode="Story",diff="Normal",act=9,amount="1x",chance="3%",pity=30},{world="Marine Lobby",mode="Story",diff="Normal",act=10,amount="1x",chance="3%",pity=30},{world="Marine Lobby",mode="Story",diff="Hard",act=9,amount="1x",chance="6%",pity=15},{world="Marine Lobby",mode="Story",diff="Hard",act=10,amount="1x",chance="6%",pity=15} },
        ["Shinobi Bone"]         = { {world="Ninja Village",mode="Story",diff="Normal",act=1,amount="2-4x",chance="100%"},{world="Ninja Village",mode="Story",diff="Normal",act=2,amount="2-4x",chance="100%"},{world="Ninja Village",mode="Story",diff="Hard",act=1,amount="4-8x",chance="100%"},{world="Ninja Village",mode="Story",diff="Hard",act=2,amount="4-8x",chance="100%"} },
        ["Binding Cloth"]        = { {world="Ninja Village",mode="Story",diff="Normal",act=3,amount="1-2x",chance="100%"},{world="Ninja Village",mode="Story",diff="Normal",act=4,amount="1-2x",chance="100%"},{world="Ninja Village",mode="Story",diff="Hard",act=3,amount="2-4x",chance="100%"},{world="Ninja Village",mode="Story",diff="Hard",act=4,amount="2-4x",chance="100%"} },
        ["Genjutsu Fog Vial"]    = { {world="Ninja Village",mode="Story",diff="Normal",act=5,amount="1x",chance="100%"},{world="Ninja Village",mode="Story",diff="Normal",act=6,amount="1x",chance="100%"},{world="Ninja Village",mode="Story",diff="Hard",act=5,amount="2x",chance="100%"},{world="Ninja Village",mode="Story",diff="Hard",act=6,amount="2x",chance="100%"} },
        ["Fuin Script Paper"]    = { {world="Ninja Village",mode="Story",diff="Normal",act=7,amount="1x",chance="30%"},{world="Ninja Village",mode="Story",diff="Normal",act=8,amount="1x",chance="30%"},{world="Ninja Village",mode="Story",diff="Hard",act=7,amount="1x",chance="60%"},{world="Ninja Village",mode="Story",diff="Hard",act=8,amount="1x",chance="60%"} },
        ["Chakra Fragment"]      = { {world="Ninja Village",mode="Story",diff="Normal",act=9,amount="1x",chance="3%",pity=30},{world="Ninja Village",mode="Story",diff="Normal",act=10,amount="1x",chance="3%",pity=30},{world="Ninja Village",mode="Story",diff="Hard",act=9,amount="1x",chance="6%",pity=15},{world="Ninja Village",mode="Story",diff="Hard",act=10,amount="1x",chance="6%",pity=15} },
        ["Brand Ash"]            = { {world="Eclipse (Before)",mode="Story",diff="Normal",act=5,amount="1x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Normal",act=6,amount="1x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Hard",act=5,amount="2x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Hard",act=6,amount="2x",chance="100%"} },
        ["Moonlit Silver"]       = { {world="Eclipse (Before)",mode="Story",diff="Normal",act=7,amount="1x",chance="30%"},{world="Eclipse (Before)",mode="Story",diff="Normal",act=8,amount="1x",chance="30%"},{world="Eclipse (Before)",mode="Story",diff="Hard",act=7,amount="1x",chance="60%"},{world="Eclipse (Before)",mode="Story",diff="Hard",act=8,amount="1x",chance="60%"} },
        ["Black Sun Amber"]      = { {world="Eclipse (Before)",mode="Story",diff="Normal",act=9,amount="1x",chance="3%",pity=30},{world="Eclipse (Before)",mode="Story",diff="Normal",act=10,amount="1x",chance="3%",pity=30},{world="Eclipse (Before)",mode="Story",diff="Hard",act=9,amount="1x",chance="6%",pity=15},{world="Eclipse (Before)",mode="Story",diff="Hard",act=10,amount="1x",chance="6%",pity=15} },
        ["Zeni"]                 = { {world="GT City",mode="Squadron",diff="Normal",act=1,amount="1-2x",chance="50%"},{world="GT City",mode="Squadron",diff="Hard",act=1,amount="1-2x",chance="100%"} },
        ["Scouter"]              = { {world="GT City",mode="Squadron",diff="Normal",act=2,amount="1x",chance="2.5%",pity=50},{world="GT City",mode="Squadron",diff="Hard",act=2,amount="1x",chance="5%",pity=30} },
        ["Power Pole"]           = { {world="GT City",mode="Squadron",diff="Normal",act=3,amount="1x",chance="2.5%",pity=50},{world="GT City",mode="Squadron",diff="Hard",act=3,amount="1x",chance="5%",pity=30} },
        ["Pelli"]                = { {world="Marine Lobby",mode="Squadron",diff="Normal",act=1,amount="1-2x",chance="50%"},{world="Marine Lobby",mode="Squadron",diff="Hard",act=1,amount="1-2x",chance="100%"} },
        ["Bisento"]              = { {world="Marine Lobby",mode="Squadron",diff="Normal",act=2,amount="1x",chance="2.5%",pity=50},{world="Marine Lobby",mode="Squadron",diff="Hard",act=2,amount="1x",chance="5%",pity=30} },
        ["Gryphon"]              = { {world="Marine Lobby",mode="Squadron",diff="Normal",act=3,amount="1x",chance="2.5%",pity=50},{world="Marine Lobby",mode="Squadron",diff="Hard",act=3,amount="1x",chance="5%",pity=30} },
        ["Headband"]             = { {world="Ninja Village",mode="Squadron",diff="Normal",act=1,amount="1-2x",chance="50%"},{world="Ninja Village",mode="Squadron",diff="Hard",act=1,amount="1-2x",chance="100%"} },
        ["Karashi's Book"]       = { {world="Ninja Village",mode="Squadron",diff="Normal",act=2,amount="1x",chance="2.5%",pity=50},{world="Ninja Village",mode="Squadron",diff="Hard",act=2,amount="1x",chance="5%",pity=30} },
        ["Shuriken"]             = { {world="Ninja Village",mode="Squadron",diff="Normal",act=3,amount="1x",chance="2.5%",pity=50},{world="Ninja Village",mode="Squadron",diff="Hard",act=3,amount="1x",chance="5%",pity=30} },
        ["Gunbai"]               = { {world="Ninja Village",mode="Squadron",diff="Normal",act=4,amount="1x",chance="0.5%",pity=200},{world="Ninja Village",mode="Squadron",diff="Hard",act=4,amount="1x",chance="2%",pity=100} },
        ["Madora"]               = { {world="Ninja Village",mode="Squadron",diff="Normal",act=4,amount="1x",chance="0.25%",pity=300},{world="Ninja Village",mode="Squadron",diff="Hard",act=4,amount="1x",chance="0.5%",pity=200} },
        ["Caskas Sword"]         = { {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=2,amount="1x",chance="2.5%",pity=50},{world="Eclipse (Before)",mode="Squadron",diff="Hard",act=2,amount="1x",chance="5%",pity=30} },
        ["Cavalry Saber"]        = { {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=3,amount="1x",chance="2.5%",pity=50},{world="Eclipse (Before)",mode="Squadron",diff="Hard",act=3,amount="1x",chance="5%",pity=30} },
        ["Dragon Slayer (Evo)"]  = { {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=4,amount="1x",chance="2%",pity=100} },
        ["Berserker"]            = { {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=4,amount="1x",chance="0.25%",pity=300},{world="Eclipse (Before)",mode="Squadron",diff="Hard",act=4,amount="1x",chance="0.5%",pity=200} },
        ["Behelit"]              = { {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=1,amount="1-2x",chance="50%"},{world="Eclipse (Before)",mode="Squadron",diff="Hard",act=1,amount="1-2x",chance="100%"} },
        ["Dragonballs"]          = { {world="GT City",mode="Raid",diff="Normal",act=4,amount="1x",chance="0.5%",pity=200},{world="GT City",mode="Raid",diff="Hard",act=4,amount="1x",chance="1%",pity=100} },
        ["Shanron"]              = { {world="GT City",mode="Raid",diff="Normal",act=4,amount="1x",chance="0.25%",pity=400},{world="GT City",mode="Raid",diff="Hard",act=4,amount="1x",chance="0.5%",pity=200} },
        ["White Behelit"]        = { {world="Eclipse (Before)",mode="Raid",diff="Normal",act=1,amount="1-2x",chance="50%"},{world="Eclipse (Before)",mode="Raid",diff="Normal",act=2,amount="1-2x",chance="50%"},{world="Eclipse (Before)",mode="Raid",diff="Normal",act=3,amount="1-2x",chance="50%"},{world="Eclipse (Before)",mode="Raid",diff="Normal",act=4,amount="1-2x",chance="50%"},{world="Eclipse (Before)",mode="Raid",diff="Hard",act=1,amount="1-2x",chance="100%"},{world="Eclipse (Before)",mode="Raid",diff="Hard",act=2,amount="1-2x",chance="100%"},{world="Eclipse (Before)",mode="Raid",diff="Hard",act=3,amount="1-2x",chance="100%"},{world="Eclipse (Before)",mode="Raid",diff="Hard",act=4,amount="1-2x",chance="100%"} },
        ["Sword Of Resonance"]   = { {world="Eclipse (Before)",mode="Raid",diff="Normal",act=4,amount="1x",chance="0.5%",pity=200},{world="Eclipse (Before)",mode="Raid",diff="Hard",act=4,amount="1x",chance="1%",pity=100} },
        ["Skeleton Knight"]      = { {world="Eclipse (Before)",mode="Raid",diff="Normal",act=4,amount="1x",chance="0.25%",pity=400},{world="Eclipse (Before)",mode="Raid",diff="Hard",act=4,amount="1x",chance="0.5%",pity=200} },
        ["Narutomaki"]           = { {world="Ninja Village",mode="Squadron",diff="Normal",act=1,amount="4-6x",chance="100%"},{world="Ninja Village",mode="Squadron",diff="Normal",act=2,amount="4-6x",chance="100%"},{world="Ninja Village",mode="Squadron",diff="Normal",act=3,amount="4-6x",chance="100%"},{world="Ninja Village",mode="Squadron",diff="Normal",act=4,amount="4-6x",chance="100%"},{world="Ninja Village",mode="Squadron",diff="Hard",act=1,amount="4-6x",chance="100%"},{world="Ninja Village",mode="Squadron",diff="Hard",act=2,amount="4-6x",chance="100%"},{world="Ninja Village",mode="Squadron",diff="Hard",act=3,amount="4-6x",chance="100%"},{world="Ninja Village",mode="Squadron",diff="Hard",act=4,amount="4-6x",chance="100%"} },
        ["Meat"]                 = { {world="Marine Lobby",mode="Squadron",diff="Normal",act=1,amount="4-6x",chance="100%"},{world="Marine Lobby",mode="Squadron",diff="Normal",act=2,amount="4-6x",chance="100%"},{world="Marine Lobby",mode="Squadron",diff="Normal",act=3,amount="4-6x",chance="100%"},{world="Marine Lobby",mode="Squadron",diff="Hard",act=1,amount="4-6x",chance="100%"},{world="Marine Lobby",mode="Squadron",diff="Hard",act=2,amount="4-6x",chance="100%"},{world="Marine Lobby",mode="Squadron",diff="Hard",act=3,amount="4-6x",chance="100%"} },
        ["Senzu"]                = { {world="GT City",mode="Squadron",diff="Normal",act=1,amount="4-6x",chance="100%"},{world="GT City",mode="Squadron",diff="Normal",act=2,amount="4-6x",chance="100%"},{world="GT City",mode="Squadron",diff="Normal",act=3,amount="4-6x",chance="100%"},{world="GT City",mode="Squadron",diff="Hard",act=1,amount="4-6x",chance="100%"},{world="GT City",mode="Squadron",diff="Hard",act=2,amount="4-6x",chance="100%"},{world="GT City",mode="Squadron",diff="Hard",act=3,amount="4-6x",chance="100%"} },
        ["Brand of Sacrifice"]   = { {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=1,amount="4-6x",chance="100%"},{world="Eclipse (Before)",mode="Squadron",diff="Normal",act=2,amount="4-6x",chance="100%"},{world="Eclipse (Before)",mode="Squadron",diff="Normal",act=3,amount="4-6x",chance="100%"},{world="Eclipse (Before)",mode="Squadron",diff="Normal",act=4,amount="4-6x",chance="100%"},{world="Eclipse (Before)",mode="Squadron",diff="Hard",act=1,amount="4-6x",chance="100%"},{world="Eclipse (Before)",mode="Squadron",diff="Hard",act=2,amount="4-6x",chance="100%"},{world="Eclipse (Before)",mode="Squadron",diff="Hard",act=3,amount="4-6x",chance="100%"},{world="Eclipse (Before)",mode="Squadron",diff="Hard",act=4,amount="4-6x",chance="100%"} },
        ["Eclipse Stone"]        = { {world="Eclipse (Before)",mode="Story",diff="Normal",act=3,amount="1-2x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Normal",act=4,amount="1-2x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Hard",act=3,amount="2-4x",chance="100%"},{world="Eclipse (Before)",mode="Story",diff="Hard",act=4,amount="2-4x",chance="100%"} },
    },

}
