-- Material -> Locations map
return {
    ["Sword Of Resonance"]={
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=4,amount="1x",chance="0.5%",pity=200},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=4,amount="1x",chance="1%",pity=100},
    },
    ["Falcon Chest"]={
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=1,amount="1x",chance="2.5%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=1,amount="1x",chance="5%"},
    },
    ["Shinobi Bone"]={
        {world="Ninja Village",mode="Story",diff="Normal",act=1,amount="2-4x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Normal",act=2,amount="2-4x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Hard",act=1,amount="4-8x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Hard",act=2,amount="4-8x",chance="100%"},
    },
    ["Currentbinder Rope"]={
        {world="Marine Lobby",mode="Story",diff="Normal",act=1,amount="2-4x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Normal",act=2,amount="2-4x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Hard",act=1,amount="4-8x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Hard",act=2,amount="4-8x",chance="100%"},
    },
    ["Genjutsu Fog Vial"]={
        {world="Ninja Village",mode="Story",diff="Normal",act=5,amount="1x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Normal",act=6,amount="1x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Hard",act=5,amount="2x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Hard",act=6,amount="2x",chance="100%"},
    },
    ["Brand Ash"]={
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=5,amount="1x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=6,amount="1x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=5,amount="2x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=6,amount="2x",chance="100%"},
    },
    ["Power Pole"]={
        {world="GT City",mode="Squadron",diff="Normal",act=3,amount="1x",chance="2.5%",pity=50},
        {world="GT City",mode="Squadron",diff="Hard",act=3,amount="1x",chance="5%",pity=30},
    },
    ["Shanron"]={
        {world="GT City",mode="Raid",diff="Normal",act=4,amount="1x",chance="0.25%",pity=400},
        {world="GT City",mode="Raid",diff="Hard",act=4,amount="1x",chance="0.5%",pity=200},
    },
    ["Omega Chest"]={
        {world="GT City",mode="Raid",diff="Normal",act=1,amount="1x",chance="2.5%"},
        {world="GT City",mode="Raid",diff="Hard",act=1,amount="1x",chance="5%"},
    },
    ["Fuin Script Paper"]={
        {world="Ninja Village",mode="Story",diff="Normal",act=7,amount="1x",chance="30%"},
        {world="Ninja Village",mode="Story",diff="Normal",act=8,amount="1x",chance="30%"},
        {world="Ninja Village",mode="Story",diff="Hard",act=7,amount="1x",chance="60%"},
        {world="Ninja Village",mode="Story",diff="Hard",act=8,amount="1x",chance="60%"},
    },
    ["Ki Resonant Crystal"]={
        {world="GT City",mode="Story",diff="Normal",act=3,amount="1-2x",chance="100%"},
        {world="GT City",mode="Story",diff="Normal",act=4,amount="1-2x",chance="100%"},
        {world="GT City",mode="Story",diff="Hard",act=3,amount="2-4x",chance="100%"},
        {world="GT City",mode="Story",diff="Hard",act=4,amount="2-4x",chance="100%"},
    },
    ["Eclipse Stone"]={
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=3,amount="1-2x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=4,amount="1-2x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=3,amount="2-4x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=4,amount="2-4x",chance="100%"},
    },
    ["Omega Coins"]={
        {world="GT City",mode="Raid",diff="Normal",act=1,amount="2-3x",chance="100%"},
        {world="GT City",mode="Raid",diff="Normal",act=2,amount="4-6x",chance="100%"},
        {world="GT City",mode="Raid",diff="Normal",act=3,amount="7-9x",chance="100%"},
        {world="GT City",mode="Raid",diff="Normal",act=4,amount="8-10x",chance="100%"},
        {world="GT City",mode="Raid",diff="Hard",act=1,amount="5-7x",chance="100%"},
        {world="GT City",mode="Raid",diff="Hard",act=2,amount="8-11x",chance="100%"},
        {world="GT City",mode="Raid",diff="Hard",act=3,amount="9-12x",chance="100%"},
        {world="GT City",mode="Raid",diff="Hard",act=4,amount="12-14x",chance="100%"},
    },
    ["Trait Shards"]={
        {world="GT City",mode="Raid",diff="Normal",act=4,amount="1-2x",chance="25%"},
        {world="GT City",mode="Raid",diff="Hard",act=4,amount="1-2x",chance="35%"},
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=4,amount="1-2x",chance="25%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=4,amount="1-2x",chance="35%"},
    },
    ["Gems"]={
        {world="GT City",mode="Story",diff="Normal",act=1,amount="5x",chance="100%"},
    },
    ["Eclipse Godstone"]={
        {world="GT City",mode="Story",diff="Normal",act=9,amount="1x",chance="3%",pity=30},
        {world="GT City",mode="Story",diff="Normal",act=10,amount="1x",chance="3%",pity=30},
        {world="GT City",mode="Story",diff="Hard",act=9,amount="1x",chance="6%",pity=15},
        {world="GT City",mode="Story",diff="Hard",act=10,amount="1x",chance="6%",pity=15},
    },
    ["King's Haki Residue"]={
        {world="Marine Lobby",mode="Story",diff="Normal",act=9,amount="1x",chance="3%",pity=30},
        {world="Marine Lobby",mode="Story",diff="Normal",act=10,amount="1x",chance="3%",pity=30},
        {world="Marine Lobby",mode="Story",diff="Hard",act=9,amount="1x",chance="6%",pity=15},
        {world="Marine Lobby",mode="Story",diff="Hard",act=10,amount="1x",chance="6%",pity=15},
    },
    ["Limitbreak Obsidian"]={
        {world="GT City",mode="Story",diff="Normal",act=7,amount="1x",chance="30%"},
        {world="GT City",mode="Story",diff="Normal",act=8,amount="1x",chance="30%"},
        {world="GT City",mode="Story",diff="Hard",act=7,amount="1x",chance="60%"},
        {world="GT City",mode="Story",diff="Hard",act=8,amount="1x",chance="60%"},
    },
    ["Apostle Iron"]={
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=1,amount="2-4x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=2,amount="2-4x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=1,amount="4-8x",chance="100%"},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=2,amount="4-8x",chance="100%"},
    },
    ["Falcon Head"]={
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=3,amount="1x",chance="2.5%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=3,amount="1x",chance="5%"},
    },
    ["Falcon Legs"]={
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=2,amount="1x",chance="2.5%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=2,amount="1x",chance="5%"},
    },
    ["Dragon Slayer (Evo)"]={
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=4,amount="1x",chance="2%",pity=100},
    },
    ["White Behelit"]={
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=1,amount="1-2x",chance="50%"},
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=2,amount="1-2x",chance="50%"},
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=3,amount="1-2x",chance="50%"},
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=4,amount="1-2x",chance="50%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=1,amount="1-2x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=2,amount="1-2x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=3,amount="1-2x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=4,amount="1-2x",chance="100%"},
    },
    ["Moonlit Silver"]={
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=7,amount="1x",chance="30%"},
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=8,amount="1x",chance="30%"},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=7,amount="1x",chance="60%"},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=8,amount="1x",chance="60%"},
    },
    ["Zenkai Ore"]={
        {world="GT City",mode="Story",diff="Normal",act=1,amount="2-4x",chance="100%"},
        {world="GT City",mode="Story",diff="Normal",act=2,amount="2-4x",chance="100%"},
        {world="GT City",mode="Story",diff="Hard",act=1,amount="4-8x",chance="100%"},
        {world="GT City",mode="Story",diff="Hard",act=2,amount="4-8x",chance="100%"},
    },
    ["Berserker"]={
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=4,amount="1x",chance="0.25%",pity=300},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=4,amount="1x",chance="0.5%",pity=200},
    },
    ["Behelit"]={
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=1,amount="1-2x",chance="50%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=1,amount="1-2x",chance="100%"},
    },
    ["Black Sun Amber"]={
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=9,amount="1x",chance="3%",pity=30},
        {world="Eclipse (Before)",mode="Story",diff="Normal",act=10,amount="1x",chance="3%",pity=30},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=9,amount="1x",chance="6%",pity=15},
        {world="Eclipse (Before)",mode="Story",diff="Hard",act=10,amount="1x",chance="6%",pity=15},
    },
    ["Dragonballs"]={
        {world="GT City",mode="Raid",diff="Normal",act=4,amount="1x",chance="0.5%",pity=200},
        {world="GT City",mode="Raid",diff="Hard",act=4,amount="1x",chance="1%",pity=100},
    },
    ["Caskas Sword"]={
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=2,amount="1x",chance="2.5%",pity=50},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=2,amount="1x",chance="5%",pity=30},
    },
    ["Senzu"]={
        {world="GT City",mode="Story",diff="Normal",act=1,amount="1-2x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Normal",act=1,amount="4-6x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Normal",act=2,amount="4-6x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Normal",act=3,amount="4-6x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Hard",act=1,amount="4-6x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Hard",act=2,amount="4-6x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Hard",act=3,amount="4-6x",chance="100%"},
    },
    ["Brand of Sacrifice"]={
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=1,amount="4-6x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=2,amount="4-6x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=3,amount="4-6x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=4,amount="4-6x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=1,amount="4-6x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=2,amount="4-6x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=3,amount="4-6x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=4,amount="4-6x",chance="100%"},
    },
    ["Cavalry Saber"]={
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=3,amount="1x",chance="2.5%",pity=50},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=3,amount="1x",chance="5%",pity=30},
    },
    ["Beastblood Catalyst"]={
        {world="Marine Lobby",mode="Story",diff="Normal",act=7,amount="1x",chance="30%"},
        {world="Marine Lobby",mode="Story",diff="Normal",act=8,amount="1x",chance="30%"},
        {world="Marine Lobby",mode="Story",diff="Hard",act=7,amount="1x",chance="60%"},
        {world="Marine Lobby",mode="Story",diff="Hard",act=8,amount="1x",chance="60%"},
    },
    ["Gryphon"]={
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=3,amount="1x",chance="2.5%",pity=50},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=3,amount="1x",chance="5%",pity=30},
    },
    ["Skeleton Knight"]={
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=4,amount="1x",chance="0.25%",pity=400},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=4,amount="1x",chance="0.5%",pity=200},
    },
    ["Omega Legs"]={
        {world="GT City",mode="Raid",diff="Normal",act=2,amount="1x",chance="2.5%"},
        {world="GT City",mode="Raid",diff="Hard",act=2,amount="1x",chance="5%"},
    },
    ["XP"]={
        {world="GT City",mode="Story",diff="Normal",act=1,amount="10x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Normal",act=1,amount="20x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Normal",act=2,amount="25x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Normal",act=3,amount="30x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Hard",act=1,amount="40x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Hard",act=2,amount="50x",chance="100%"},
        {world="GT City",mode="Squadron",diff="Hard",act=3,amount="75x",chance="100%"},
        {world="GT City",mode="Raid",diff="Normal",act=1,amount="20x",chance="100%"},
        {world="GT City",mode="Raid",diff="Normal",act=2,amount="20x",chance="100%"},
        {world="GT City",mode="Raid",diff="Normal",act=3,amount="30x",chance="100%"},
        {world="GT City",mode="Raid",diff="Normal",act=4,amount="20x",chance="100%"},
        {world="GT City",mode="Raid",diff="Hard",act=1,amount="30x",chance="100%"},
        {world="GT City",mode="Raid",diff="Hard",act=2,amount="30x",chance="100%"},
        {world="GT City",mode="Raid",diff="Hard",act=3,amount="30x",chance="100%"},
        {world="GT City",mode="Raid",diff="Hard",act=4,amount="30x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=1,amount="20x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=2,amount="25x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=3,amount="30x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=1,amount="40x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=2,amount="50x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=3,amount="75x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Normal",act=1,amount="20x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Normal",act=2,amount="25x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Normal",act=3,amount="30x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Normal",act=4,amount="50x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=1,amount="40x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=2,amount="50x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=3,amount="75x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=4,amount="100x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=1,amount="20x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=2,amount="25x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=3,amount="30x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Normal",act=4,amount="50x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=1,amount="40x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=2,amount="50x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=3,amount="75x",chance="100%"},
        {world="Eclipse (Before)",mode="Squadron",diff="Hard",act=4,amount="100x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=1,amount="20x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=2,amount="20x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=3,amount="30x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Normal",act=4,amount="20x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=1,amount="30x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=2,amount="30x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=3,amount="30x",chance="100%"},
        {world="Eclipse (Before)",mode="Raid",diff="Hard",act=4,amount="30x",chance="100%"},
    },
    ["Madora"]={
        {world="Ninja Village",mode="Squadron",diff="Normal",act=4,amount="1x",chance="0.25%",pity=300},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=4,amount="1x",chance="0.5%",pity=200},
    },
    ["Gunbai"]={
        {world="Ninja Village",mode="Squadron",diff="Normal",act=4,amount="1x",chance="0.5%",pity=200},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=4,amount="1x",chance="2%",pity=100},
    },
    ["Pelli"]={
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=1,amount="1-2x",chance="50%"},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=1,amount="1-2x",chance="100%"},
    },
    ["Narutomaki"]={
        {world="Ninja Village",mode="Squadron",diff="Normal",act=1,amount="4-6x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Normal",act=2,amount="4-6x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Normal",act=3,amount="4-6x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Normal",act=4,amount="4-6x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=1,amount="4-6x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=2,amount="4-6x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=3,amount="4-6x",chance="100%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=4,amount="4-6x",chance="100%"},
    },
    ["Zeni"]={
        {world="GT City",mode="Squadron",diff="Normal",act=1,amount="1-2x",chance="50%"},
        {world="GT City",mode="Squadron",diff="Hard",act=1,amount="1-2x",chance="100%"},
    },
    ["Depthglass Bottle"]={
        {world="Marine Lobby",mode="Story",diff="Normal",act=3,amount="1-2x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Normal",act=4,amount="1-2x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Hard",act=3,amount="2-4x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Hard",act=4,amount="2-4x",chance="100%"},
    },
    ["Bisento"]={
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=2,amount="1x",chance="2.5%",pity=50},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=2,amount="1x",chance="5%",pity=30},
    },
    ["Omega Horns"]={
        {world="GT City",mode="Raid",diff="Normal",act=3,amount="1x",chance="2.5%"},
        {world="GT City",mode="Raid",diff="Hard",act=3,amount="1x",chance="5%"},
    },
    ["Headband"]={
        {world="Ninja Village",mode="Squadron",diff="Normal",act=1,amount="1-2x",chance="50%"},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=1,amount="1-2x",chance="100%"},
    },
    ["Chakra Fragment"]={
        {world="Ninja Village",mode="Story",diff="Normal",act=9,amount="1x",chance="3%",pity=30},
        {world="Ninja Village",mode="Story",diff="Normal",act=10,amount="1x",chance="3%",pity=30},
        {world="Ninja Village",mode="Story",diff="Hard",act=9,amount="1x",chance="6%",pity=15},
        {world="Ninja Village",mode="Story",diff="Hard",act=10,amount="1x",chance="6%",pity=15},
    },
    ["Shuriken"]={
        {world="Ninja Village",mode="Squadron",diff="Normal",act=3,amount="1x",chance="2.5%",pity=50},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=3,amount="1x",chance="5%",pity=30},
    },
    ["Karashi's Book"]={
        {world="Ninja Village",mode="Squadron",diff="Normal",act=2,amount="1x",chance="2.5%",pity=50},
        {world="Ninja Village",mode="Squadron",diff="Hard",act=2,amount="1x",chance="5%",pity=30},
    },
    ["Stellar Ki Quartz"]={
        {world="GT City",mode="Story",diff="Normal",act=5,amount="1x",chance="100%"},
        {world="GT City",mode="Story",diff="Normal",act=6,amount="1x",chance="100%"},
        {world="GT City",mode="Story",diff="Hard",act=5,amount="2x",chance="100%"},
        {world="GT City",mode="Story",diff="Hard",act=6,amount="2x",chance="100%"},
    },
    ["Binding Cloth"]={
        {world="Ninja Village",mode="Story",diff="Normal",act=3,amount="1-2x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Normal",act=4,amount="1-2x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Hard",act=3,amount="2-4x",chance="100%"},
        {world="Ninja Village",mode="Story",diff="Hard",act=4,amount="2-4x",chance="100%"},
    },
    ["Scouter"]={
        {world="GT City",mode="Squadron",diff="Normal",act=2,amount="1x",chance="2.5%",pity=50},
        {world="GT City",mode="Squadron",diff="Hard",act=2,amount="1x",chance="5%",pity=30},
    },
    ["Meat"]={
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=1,amount="4-6x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=2,amount="4-6x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Normal",act=3,amount="4-6x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=1,amount="4-6x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=2,amount="4-6x",chance="100%"},
        {world="Marine Lobby",mode="Squadron",diff="Hard",act=3,amount="4-6x",chance="100%"},
    },
    ["Stormwake Sailcloth"]={
        {world="Marine Lobby",mode="Story",diff="Normal",act=5,amount="1x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Normal",act=6,amount="1x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Hard",act=5,amount="2x",chance="100%"},
        {world="Marine Lobby",mode="Story",diff="Hard",act=6,amount="2x",chance="100%"},
    },
}